### ISSUE TITLE
2d小人载入有错误

### ISSUE THREAD

**Issue by EvilCalf** [xb2016/kratos-pjax#12]
一个报错是：Uncaught SyntaxError: Unexpected token ,
另一个是：Failed to load http://120.78.197.104/wp-content/themes/kratos-pjax-master/inc/model/api.php?p=33&model=default: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.xujiading.top' is therefore not allowed access.
然后我已经子在nginx.conf里添加了：
add_header 'Access-Control-Allow-Origin' 'http://www.xujiading.top';
add_header 'Access-Control-Allow-Credentials' 'true';
add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,X-Requested-With';
add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS';
求大佬帮我看看

**Comment by EvilCalf** [comment]
![image](https://user-images.githubusercontent.com/35754619/42641814-fa625984-8627-11e8-8d8c-4660bb210623.png)

**Comment by xb2016** [comment]
把你站点设置里面的IP改成域名啊。。。。

**Comment by EvilCalf** [comment]
改了啊，本来还有好多错误，改了就剩这一个了

**Comment by xb2016** [comment]
可以明确说 改对了正常情况是不可能出现IP的
