### ISSUE TITLE
站点描述问题

### ISSUE THREAD

**Issue by 892768447** [xb2016/kratos-pjax#20]
emmm，大佬，求助。
关闭yoast seo插件后。每篇文章的description是酱紫的。
《meta name="description" content="相关"》
开启yoast seo插件后正常，但是/archives/ 页面 的标题和描述被强制修改为 归档里面最下面的一篇文章的标题和描述了

**Comment by xb2016** [comment]
主题默认截取文章前几十个字作为描述，我不觉得有必要使用插件。
自然，我也不会去适配一堆插件，这并不现实。

**Comment by 892768447** [comment]
关闭其他插件后。就显示成这样了。《meta name="description" content="相关"》，我再找找是哪个插件导致的
