### ISSUE TITLE
手机版网页顶部图片不能单独设置

### ISSUE THREAD

**Issue by CrazyZhang666** [xb2016/kratos-pjax#24]
手机版网页顶部图片不能单独设置，默认和电脑版一致，即使设置了图片Logo,手机版还是显示电脑版置顶的那张图片，
![snipaste_2018-11-14_10-18-59](https://user-images.githubusercontent.com/28080853/48455588-c487b800-e7f6-11e8-998e-091222eb327f.png)
![snipaste_2018-11-14_10-19-18](https://user-images.githubusercontent.com/28080853/48455589-c487b800-e7f6-11e8-8581-82dda129757a.png)
我电脑上设置的是透明图片，手机端显示一片白色，我想单独设置手机端图片，但是设置了没有效果

**Comment by xb2016** [comment]
@CrazyZhang666 
1. 去掉 `header.php:60` 中的 `background-image` 内联样式
2. 附加 CSS 写 `@media(max-width:768px){.kratos-cover.kratos-cover_2{background-image:url(图片地址)}}`

**Comment by CrazyZhang666** [comment]
表示还是不知道怎么修改 
可不可以在主题里加上这个设置手机端图片的功能 我记得以前就有的 更新后就没了

**Comment by xb2016** [comment]
Updated.
