### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by PeterJin0703** [xb2016/kratos-pjax#29]
用了dalao的主题之后，配置都行但是不知道为什么博客里面的主题显示不出来……但是在预览的效果下是可以的。publish之后不知道为什么就显示不出来了。

**Comment by PeterJin0703** [comment]
降级至4.9.4也无效。博客地址peterjin.xyz（求各位dalao不要爆破）

**Comment by xb2016** [comment]
![default](https://user-images.githubusercontent.com/31783875/50371012-91062d80-05ed-11e9-8e96-44801453074d.png)
![default](https://user-images.githubusercontent.com/31783875/50371014-9f544980-05ed-11e9-9695-9aa461ff23e1.png)
与主题没任何关系 请自己排查。

**Comment by PeterJin0703** [comment]
好的吧…谢谢dalao指点…

**Comment by WeirdStar0** [comment]
目前测试出来插件a3 Lazy Load会导致文章页图片一直加载，无法显示
