### ISSUE TITLE
发现俩个bug噢

### ISSUE THREAD

**Issue by marlkiller** [xb2016/kratos-pjax#32]
1. 在 在已有 Aplayer 插件的情况下 , 主题设置没有开启Aplayer , 但是它会初始化 并且加载俩次噢
2. pjax加载文章的情况下 , 根据摘要wp-jam toc  跳转锚点的时候会在新窗口打开页面 , 如果Ctrl+Shift+R 强制刷新 , 则会在当前该页面跳转

**Comment by xb2016** [comment]
有相关需求请自行适配。
