### ISSUE TITLE
求修复bug

### ISSUE THREAD

**Issue by 30115776** [xb2016/kratos-pjax#33]
今天刚刚使用了这个主题，觉得非常棒，非常喜欢。提几个小意见。
1、网站似乎缺少一个搜索网站的小工具。
2、右上角加入一个登录注册，也许会吸引更多人登录注册。
3、网站的优化非常棒，缺少一个网站地图、AMP or MIP 是否有考虑过呢？
4、友情链接那个 页面好像bug。

LNMP
1.5 + 5.7 + 7.3

**Comment by Sokwva** [comment]
网站地图不是有吗_(:зゝ∠)_

**Comment by xb2016** [comment]
@30115776 首先感谢提意见，但是本次不作更改。

1.主题自带全局搜索按钮 小工具无意义
2.点击个人简介小工具的头像即可登录，自己也可在菜单添加登录选项
3.主题自带 sitemap
4.未发现问题
