### ISSUE TITLE
Jetpack插件无法正常工作

### ISSUE THREAD

**Issue by XMD0718** [xb2016/kratos-pjax#42]
在后台安装了Jetpack插件后，出现如下提示：Warning: call_user_func_array() expects parameter 1 to be a valid callback, function '_return_false' not found or invalid function name in /www/wwwroot/www.xunmengdu.com/wp-includes/class-wp-hook.php on line 286
并显示WordPress REST API 已禁用

更换其他主题后插件恢复正常使用
很喜欢作者的魔改Kratos主题，不想更换其他主题，但又想使用Jetpack的服务。希望作者能够更新一下，将这个问题修复。
万分感激！

**Comment by xb2016** [comment]
关于启用 REST API 问题，可尝试注释掉 core.php: 126 140 141 146 行

**Comment by XMD0718** [comment]
注释掉这几行后，Jetpack插件已恢复工作，感谢回复，希望将此加入下一次更新中
