### ISSUE TITLE
侧边栏文章聚合背景不能半透明

### ISSUE THREAD

**Issue by CrazyZhang666** [xb2016/kratos-pjax#46]
在设置主题背景为图片时，我发现侧边栏文章聚合背景不能半透明，背景还是纯白色，虽然不影响使用，但是看起来很难受
![image](https://user-images.githubusercontent.com/28080853/61842417-abc5bb00-aeca-11e9-9f86-c2d9c3b3cd26.png)
有白块，而不是半透明效果

**Comment by xb2016** [comment]
插件原因 自行解决

**Comment by CrazyZhang666** [comment]
哇 duang的一下就解决啦！感谢大佬
