### ISSUE TITLE
关于pjax的问题

### ISSUE THREAD

**Issue by zklovewm** [xb2016/kratos-pjax#50]
你好，请问一下开启了pjax之后一些插件（比如hermit播放器），插入文章之后在博客页面打开文章无法正常加载出插件，必须要刷新页面才行.。这个问题怎么解决

**Comment by xb2016** [comment]
在 `kratos-pjax/static/js/kratos.js:257` 的 **pjax reload** 中加入插件的重载函数，重载函数是什么请尝试谷歌或询问插件作者。添加完成后保存，然后关闭主题设置中的 **从jsdelivr加载主题JS** 选项即可。

**Comment by zklovewm** [comment]
那个重载函数是reloadHermit();
但是我加进去没有反应 请问具体是加在什么位置

**Comment by xb2016** [comment]
`$.fn.kratos_pjax_reload = function(){}` 里面 已经有三个重载函数了

**Comment by zklovewm** [comment]
好的 谢谢 已经解决了
