### ISSUE TITLE
如何添加随机的图片

### ISSUE THREAD

**Issue by laoxong** [xb2016/kratos-pjax#51]
是直接复制到图片文件夹吗，用不用改文件，还有图片的名字有没有要求，只支持jpg？
以及看板娘的皮肤如何更新

**Comment by enjoyuruf** [comment]
使用相同名称替换其中文件是最为稳妥的

**Comment by laoxong** [comment]
> 使用相同名称替换其中文件是最高稳妥的

但是我想添加几张照片，有的时候会出现重复的,z最后是支持API调用图片
http://toss.ztuck.vip/api/rcysxt/api.php
像这种
