### ISSUE TITLE
滚动条可能存在问题

### ISSUE THREAD

**Issue by 1026831402** [xb2016/kratos-pjax#54]
添加Canvas-Nest.js插件或者使用Font Awesome库中动态的字体库链接，滚动条90%会变黑，使用的是浏览器是360极速2216版，切换兼容模式问题消失，更换为其他的滚动条样式问题消失，在你的博客上偶尔也会出现一瞬间的90%的滚动条变黑

**Comment by xb2016** [comment]
你可以选择移除我定义的样式 `kratos.min.css : 24`
