### ISSUE TITLE
[BUG]在添加了统计代码之后前端显示问题

### ISSUE THREAD

**Issue by acutecat** [xb2016/kratos-pjax#57]
**站点地址**
https://mmdfans.com
请提供出现问题的站点 URL
全站
**产生环境**
php73，NG1.15，MySql5.5
- 设备：
- 浏览器及版本：
Chromium 74.0.3729.169
**是否在我的博客站点复现**
你的站点没有开启相应模块
如果否，你可能需要先检查自己的配置

**预期现象**

本来应该是怎么样的？
本来添加玩统计代码之后，应是显示在页脚之内
**实际现象**
实际上显示在页脚之外，成为一个没有控制的标签
出现了什么问题？
统计代码没有正确的显示在全站页脚。
**复现步骤**

1.添加统计代码
2.刷新首页，问题出现

后台设置：
![2](https://user-images.githubusercontent.com/33690786/70586728-e5415d80-1c02-11ea-801f-6e0efd4e0a84.png)

复现如图：
![1](https://user-images.githubusercontent.com/33690786/70586556-61877100-1c02-11ea-9cee-8999f6445ce2.png)

**其它信息**

PHP 错误日志等(如果有的话)

**Comment by xb2016** [comment]
CNZZ 毒瘤操作 建议使用谷歌统计 再次可以使用百度统计
