### ISSUE TITLE
[BUG] 修改部分文字标识 以符合工信部要求

### ISSUE THREAD

**Issue by coderstory** [xb2016/kratos-pjax#59]
**站点地址**

请提供出现问题的站点 URL

**产生环境**

- 设备：
- 浏览器及版本：

**是否在我的博客站点复现**

如果否，你可能需要先检查自己的配置

**预期现象**

本来应该是怎么样的？

**实际现象**

出现了什么问题？
https://help.aliyun.com/document_detail/146190.html?&msctype=email&mscareaid=cn&mscsiteid=cn&mscmsgid=4270119122000725064&&spm=a2c4k.13817982.zh-cnc.1&#title-1oz-nkb-91m
阿里发了邮件，要求整改，抓到罚款5000+，希望模板能修改一下。
比如版权所有的格式。

**复现步骤**

1.
2.

**其它信息**

PHP 错误日志等(如果有的话)

**Comment by coderstory** [comment]
工信部的地址外链 http://www.beian.miit.gov.cn

**Comment by coderstory** [comment]
尊敬的用户，您好：
--
 
  | 根据《非经营性互联网信息服务备案管理办法》（原信息产业部令第33号令）规定，非经营性互联网信息服务提供者应当在其网站开通时在主页底部的中央位置标明其备案编号，并在备案编号下方按要求链接信息产业部备案管理系统网址，供公众查询核对；如果未在其备案编号下方链接信息产业部备案管理系统网址的，由住所所在地省通信管理局责令改正，并处五千元以上一万元以下罚款。依照浙江省通信管理局近期监管要求通知，请您于12月25日前按照法规要求，做好已备案网站主页备案编号的悬挂和链接工作，链接须指向工信部网站（http://www.beian.miit.gov.cn）。若逾期未整改，将面临监管部门处罚风险。 操作指南如已完成整改，请忽略该邮件。

**Comment by xb2016** [comment]
我不觉得我写的有问题，如果你觉得有问题，请自行修改
