### ISSUE TITLE
与Crayon Syntax Highlighter不兼容

### ISSUE THREAD

**Issue by changjiale** [xb2016/kratos-pjax#6]
用Crayon Syntax Highlighter贴代码后 可以显示，但无法选中代码，代码栏上方操作栏点击全部无效
![image](https://user-images.githubusercontent.com/28778581/39966600-5bf23938-56e1-11e8-9d70-a34ef2a85e87.png)

**Comment by xb2016** [comment]
@changjiale 需要在Kratos.js pjax重载函数区重载相关js函数。这个锅我不打算处理了。
