### ISSUE TITLE
关于主页手机浏览，划屏返回问题

### ISSUE THREAD

**Issue by hotmop** [xb2016/kratos-pjax#62]
有这么个问题 测试了我自己苹果手机chrome，alook uc 安卓手机浏览器chrome 自带。点击首页随便一个主题文章，正常情况下，使用划屏返回首页，大概率的返回上上个页面，或者是当前页面。遇到这样情况是不是需要把主题删除，重新安装？我是从最新版本升上来的，每次是直接覆盖。困扰很久了。而且切换到其他主题没事哦.

**Comment by xb2016** [comment]
我未遇到此问题 你可以选择关闭主题设置中的 ajax 加载试试
