### ISSUE TITLE
[BUG]后台更改歌单JSON地址无效

### ISSUE THREAD

**Issue by XMD0718** [xb2016/kratos-pjax#63]
我已在后台修改了API地址，为什么仍然会从内置的API地址加载
![TIM截图20200214002822](https://user-images.githubusercontent.com/41297263/74455995-26831180-4ec1-11ea-9f13-7c5d350aa146.png)

**Comment by xb2016** [comment]
经查看代码与本地测试 未复现此问题 请检查自己的设置
