### ISSUE TITLE
请求添加一个文章列表不展示图片的选项

### ISSUE THREAD

**Issue by NiTian1207** [xb2016/kratos-pjax#66]
![QQ截图20200316161548](https://user-images.githubusercontent.com/40469236/76736268-79423880-67a1-11ea-9114-2778e80fcd30.png)
就是可以选择关闭前面的图片

**Comment by Howard20181** [comment]
> ![QQ截图20200316161548](https://user-images.githubusercontent.com/40469236/76736268-79423880-67a1-11ea-9114-2778e80fcd30.png)
> 就是可以选择关闭前面的图片

主题设置->站点设置->文章列表布局
