### ISSUE TITLE
看板娘不显示

### ISSUE THREAD

**Issue by laimumu** [xb2016/kratos-pjax#71]
为啥我主题的看板娘不显示，文字倒是显示了，从github上面下载安装插件也是显示不了

**Comment by xb2016** [comment]
[文档](https://moedog.org/787.html)内已写明 **9. Live2D 看板娘要求服务器启用下列 MIME 类型：.json / .moc / .mtn。**
请尝试使用搜索引擎帮助解决此问题。

**Comment by laimumu** [comment]
我用的是nginx，看了下默认应该是启动了的

**Comment by xb2016** [comment]
请提供站点地址 我看看

**Comment by laimumu** [comment]
5211314.ltd

**Comment by xb2016** [comment]
Parse error: syntax error, unexpected '[' in /www/wwwroot/5211314.ltd/wp-content/themes/kratos-pjax-master/inc/model/api.php on line 41
你是否修改了 api.php？如果没有，那么我的代码并没有问题，请尝试使用 PHP 7.3 再试。

**Comment by laimumu** [comment]
没有修改，切换了PHP版本能用了，非常感谢
