### ISSUE TITLE
[BUG] 关于存在XSS漏洞的报告

### ISSUE THREAD

**Issue by Writeup001** [xb2016/kratos-pjax#72]
# 版本信息：
WordPress 版本：5.4

# 详情介绍：
在使用此主题时，如果在编辑器以文本模式进行文章书写。如果输入了恶意代码，比如：```<script>alert(/xss/)</script>```等能造成 XSS 攻击的代码，那么将会触发 XSS 攻击。较为严重的后果则是盗取 Cookie 信息，希望能够尽快修复。

# 我的发现：
我发现其实是因为 ```<``` ```>``` 标签符号造成的，在正常的可视化编辑模式中会自动进行转义而在文本模式中则不会转义，我的建议是在存入数据库时进行转义操作，或者如有其它更好的方法也可以进行修复。另外，对于 PHP 代码，如果在文本模式下输入了 PHP 代码，比如 ```<?php phpinfo(); ?>```，即使使用了 <code> 或者 <pre> 将其包裹，仍是不能正常显示，所以我将这些问题均归为是因为 ```<``` ```>``` 标签符号造成的，希望能够修复。

# 附图：
1.文本编辑模式
![图片](https://s1.ax1x.com/2020/04/16/JEAoSU.png)

2.执行了 XSS 代码
![图片](https://s1.ax1x.com/2020/04/16/JEEn1S.png)

3.代码被插入 HTTML 中
![图片](https://s1.ax1x.com/2020/04/16/JEEF0A.png)

**Comment by xb2016** [comment]
![图片](https://user-images.githubusercontent.com/31783875/79518072-b04a8900-8082-11ea-86e4-7d261a472cb6.png)
这边建议换别的主题试试呢

**Comment by Jia0liang** [comment]
写个正则直接过滤掉script标签？

**Comment by Pragmatism0220** [comment]
这个问题其实很好解决。其实对我而言我觉得最应该恐惧的是评论区。评论区可以随便的插入html标记，包括各种恶意代码。因此对于文章或者是评论区，这种问题有个统一的、很方便的解决方法：
禁用html标记。如果有需要，一律使用短代码进行操作。

具体方法：
一、禁用html标记
打开主题目录下的functions.php，在<?php后输入：
```php
function  comment_code_filter($incoming_comment){
    $incoming_comment = htmlspecialchars($incoming_comment,ENT_QUOTES);
    return $incoming_comment;
}
add_filter( 'comment_text','comment_code_filter');
add_filter( 'comment_text_rss','comment_code_filter');
add_filter('the_content','comment_code_filter');
```
![如图所示](https://user-images.githubusercontent.com/55100969/81494011-ba555580-92d7-11ea-8b6b-965ef8a9d7c5.png)
这样就将评论区、帖子中的html标记完全过滤掉了。这么改的好处是可以在评论和文章中展示代码。如果你希望去除所有代码标签，只留下文字内容，请将过滤函数改成如下：
```php
function comment_code_filter($incoming_comment){
    $incoming_comment = strip_tags($incoming_comment);
    return $incoming_comment;
}
```
如果想自定义部分标签，则需要修改在wp-includes文件夹下的kses.php文件。在其中设置是否可以使用html标签。

二、使用短代码进行操作
对我而言，我使用短代码进行了代替。为了使评论区也支持短代码，我简单地插入了`add_filter('comment_text','do_shortcode');`。为了偷懒，我直接把这句代码放在了`/inc/ua.php`文件的最后——这样做是不符合规范的，但是却很省事。所以我这么做了。对于文章的`'the_content'`类似，就不再多说了。

希望对你有帮助。
