### ISSUE TITLE
[请求]能否删除一下后台的通知233

### ISSUE THREAD

**Issue by Small-SaltedFish** [xb2016/kratos-pjax#77]
大佬打扰了，如果您感到生气的话直接关闭即可。
嗨，欢迎使用 Kratos 主题开始创作，单击 此处 查看帮助文档。主题原作者Q群：734508。Bug 或建议请前往 Github 提交，谢谢！
这个可以允许我关闭嘛awwww强迫症好难受但是大佬的主题又牛逼...
它可以出现在”感谢使用WordPress进行创作。“旁边嘛awww
冒犯了抱歉

**Comment by Howard20181** [comment]
> 大佬打扰了，如果您感到生气的话直接关闭即可。
> 嗨，欢迎使用 Kratos 主题开始创作，单击 此处 查看帮助文档。主题原作者Q群：734508。Bug 或建议请前往 Github 提交，谢谢！
> 这个可以允许我关闭嘛awwww强迫症好难受但是大佬的主题又牛逼...
> 它可以出现在”感谢使用WordPress进行创作。“旁边嘛awww
> 冒犯了抱歉

主题设置->站点设置->通知设置->隐藏全部
