### ISSUE TITLE
[BUG] 0.4.4 版本安裝後似乎還是 0.4.3 ?

### ISSUE THREAD

**Issue by lekoOwO** [xb2016/kratos-pjax#78]
**站点地址**

https://blog.leko.moe

**复现步骤**

1. [下載](https://github.com/xb2016/kratos-pjax/archive/0.4.4.zip) ，修改資料夾名稱 (`kratos-pjax-0.4.4` -> `kratos-pjax`)並上傳至 Wordpress 更新佈景主題
2. 發現佈景主題版本仍為 0.4.3 版本，且提示網站出現重大錯誤。

**Comment by xb2016** [comment]
版本号就一个文件没改 不影响的
我这里测试是没有错误的 出错的 inc/ua.php 你可以看看替换成功了没有

**Comment by lekoOwO** [comment]
um 更改版本號之後就沒有錯誤了
看來是遇到了神奇的 bug ˊˋ
