### ISSUE TITLE
Bug:看板娘处点击首页不能Pjax

### ISSUE THREAD

**Issue by HaoZiBlog** [xb2016/kratos-pjax#9]
**问题不算太大，但对于使用音乐播放器的网站来说就会导致音乐中断。测试Bug存在的网址：1.https://www.fczbl.vip 2.https://haozi.net.cn 还望尽快修复。谢谢**

**Comment by xb2016** [comment]
这并不是bug。相关代码是直接从插件复制过来的，本来就没打算支持pjax，毕竟大多数主题并没有pjax。
以及我不觉得有人去点这里的主页按钮，建议是把主页放菜单栏。

**Comment by xb2016** [comment]
下一次版本更新估计需要等一个月。

**Comment by HaoZiBlog** [comment]
哦
